<?
//APPLICATION GENERAL
$sql = 
"CREATE TABLE colleges(
	id INT(4) PRIMARY KEY UNSIGNED AUTO_INCERMENT,
	name VARCHAR(30) NOT NULL
)"

$sql = 
"CREATE TABLE posts(
	id INT(6) PRIMARY KEY UNSIGNED AUTO_INCERMENT,
	titel VARCHAR(30) NOT NULL,
	content TEXT() NOT NULL,
	summary VARCHAR(200) NOT NULL,
	author_id INT(9) UNSIGNED UNIQUE,
	author_type INT(4) UNSIGNED,
	picturs VARCHAR(8) UNSIGNED UNIQUE,
	/*link VARCHAR(8) UNSIGNED UNIQUE,*/
	created_at TIMESTAMP()
)"
$sql = 
"CREATE TABLE posts_colleges(
	post_id INT(6) NOT NULL,
	college_id INT(4) NOT NULL
)"
/*
$sql = 
"CREATE TABLE user_picturs(
	id INT(9) PRIMARY KEY UNSIGNED AUTO_INCERMENT,
	user_id VARCHAR(9) NOT NULL UNIQUE,
	user_type VARCHAR(4) NOT NULL,
	link VARCHAR(8) UNSIGNED UNIQUE,
)"
$sql = 
"CREATE TABLE user_type(
	id INT(4) PRIMARY KEY UNSIGNED AUTO_INCERMENT,
	titel VARCHAR(30) NOT NULL,
	description VARCHAR(50) NOT NULL
)"
$sql = 
"CREATE TABLE courses(
	id INT(6) PRIMARY KEY UNSIGNED AUTO_INCERMENT,
	titel VARCHAR(30) NOT NULL,
)"